#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include <audioclient.h>
#include <mmdeviceapi.h>
#include <devicetopology.h>
#include <functiondiscoverykeys_devpkey.h>
#include <cfgmgr32.h>
#include <ksmedia.h>
#include <wrl/client.h>
#include "capture/WindowsFixturePlayer.h"
#include "capture/WindowsCaptureInput.h"
#include "capture/CaptureVerifier.h"
#include <algorithm>
#include <cstring>
#include <stdexcept>

namespace asb::capture {
namespace {
struct OrderlyFixtureStop {};
using Microsoft::WRL::ComPtr;
void check(HRESULT result,const char* what) { if(FAILED(result)) throw std::runtime_error(std::string(what)+"; HRESULT="+std::to_string(result)); }
bool belongsToSession(IMMDevice* endpoint,IMMDeviceEnumerator* enumerator,const std::wstring& serial) {
    ComPtr<IDeviceTopology> topology;
    if(FAILED(endpoint->Activate(__uuidof(IDeviceTopology),CLSCTX_INPROC_SERVER,nullptr,reinterpret_cast<void**>(topology.GetAddressOf())))) return false;
    ComPtr<IConnector> connector; if(FAILED(topology->GetConnector(0,&connector))) return false;
    LPWSTR id=nullptr; if(FAILED(connector->GetDeviceIdConnectedTo(&id))) return false;
    ComPtr<IMMDevice> controller; const auto result=enumerator->GetDevice(id,&controller); CoTaskMemFree(id);
    if(FAILED(result)) return false;
    ComPtr<IPropertyStore> properties; if(FAILED(controller->OpenPropertyStore(STGM_READ,&properties))) return false;
    PROPVARIANT value; PropVariantInit(&value);
    const auto property=properties->GetValue(PKEY_Device_InstanceId,&value);
    std::wstring instance;
    if(SUCCEEDED(property) && value.vt==VT_LPWSTR && value.pwszVal) instance=value.pwszVal;
    PropVariantClear(&value);
    if(instance.empty()) return false;
    DEVINST node=0; if(CM_Locate_DevNodeW(&node,instance.data(),CM_LOCATE_DEVNODE_NORMAL)!=CR_SUCCESS) return false;
    // Walk from the audio function to its USB parent. The serial was randomly
    // generated by this backend before attach, not supplied as an endpoint name.
    const auto expected=L"USB\\VID_054C&PID_0CE6\\"+serial;
    for(unsigned depth=0;depth<12;++depth) {
        wchar_t current[MAX_DEVICE_ID_LEN]{};
        if(CM_Get_Device_IDW(node,current,MAX_DEVICE_ID_LEN,0)!=CR_SUCCESS) return false;
        if(_wcsicmp(current,expected.c_str())==0) return true;
        DEVINST parent=0; if(CM_Get_Parent(&parent,node,0)!=CR_SUCCESS) return false; node=parent;
    }
    return false;
}
}
WindowsFixturePlayer::~WindowsFixturePlayer() { stop(); }
void WindowsFixturePlayer::start(std::filesystem::path wav,std::string serial,FeedbackRecorder& recorder) {
    if(worker_.joinable()) throw std::runtime_error("fixture player is single-use");
    worker_=std::thread([this,wav=std::move(wav),serial=std::move(serial),&recorder]{run(wav,serial,recorder);});
}
void WindowsFixturePlayer::stop(bool orderly) { if(orderly)orderly_=true;stop_=true; if(worker_.joinable()) worker_.join(); }
void WindowsFixturePlayer::run(const std::filesystem::path& wav,const std::string& serial,FeedbackRecorder& recorder) noexcept {
    const auto initialized=CoInitializeEx(nullptr,COINIT_MULTITHREADED);
    try {
        check(initialized,"fixture COM initialization failed");
        const auto pcm=loadFixturePcm(wav);
        if(pcm.size()>384000*60) throw std::runtime_error("fixture playback exceeds 60 seconds");
        ComPtr<IMMDeviceEnumerator> enumerator;
        check(CoCreateInstance(__uuidof(MMDeviceEnumerator),nullptr,CLSCTX_INPROC_SERVER,IID_PPV_ARGS(&enumerator)),"audio enumeration failed");
        ComPtr<IMMDevice> selected;
        const auto discoveryEnd=std::chrono::steady_clock::now()+std::chrono::seconds(5);
        do {
            ComPtr<IMMDeviceCollection> endpoints;
            check(enumerator->EnumAudioEndpoints(eRender,DEVICE_STATE_ACTIVE,&endpoints),"render enumeration failed");
            UINT count=0; check(endpoints->GetCount(&count),"endpoint count failed");
            unsigned matches=0;
            for(UINT i=0;i<count;++i) {
                ComPtr<IMMDevice> endpoint; check(endpoints->Item(i,&endpoint),"endpoint lookup failed");
                if(belongsToSession(endpoint.Get(),enumerator.Get(),wide(serial))) { selected=endpoint; ++matches; }
            }
            if(matches>1) throw std::runtime_error("ambiguous virtual render endpoints");
            if(matches==1) break;
            if(stop_&&orderly_)throw OrderlyFixtureStop{};
            if(stop_) throw std::runtime_error("fixture playback cancelled");
            std::this_thread::sleep_for(std::chrono::milliseconds(50));
        } while(std::chrono::steady_clock::now()<discoveryEnd);
        if(!selected) throw std::runtime_error("no render endpoint associated with this virtual session serial");
        LPWSTR rawId=nullptr; check(selected->GetId(&rawId),"endpoint identity failed");
        endpoint_=utf8(rawId); CoTaskMemFree(rawId);
        ComPtr<IAudioClient> client;
        check(selected->Activate(__uuidof(IAudioClient),CLSCTX_INPROC_SERVER,nullptr,reinterpret_cast<void**>(client.GetAddressOf())),"audio client activation failed");
        WAVEFORMATEXTENSIBLE format{};
        format.Format={WAVE_FORMAT_EXTENSIBLE,4,48000,384000,8,16,22};
        format.Samples.wValidBitsPerSample=16;
        format.dwChannelMask=SPEAKER_FRONT_LEFT|SPEAKER_FRONT_RIGHT|SPEAKER_BACK_LEFT|SPEAKER_BACK_RIGHT;
        format.SubFormat=KSDATAFORMAT_SUBTYPE_PCM;
        if(client->IsFormatSupported(AUDCLNT_SHAREMODE_EXCLUSIVE,&format.Format,nullptr)!=S_OK)
            throw std::runtime_error("exact exclusive four-channel s16le format unsupported; no conversion fallback");
        REFERENCE_TIME period=0; check(client->GetDevicePeriod(nullptr,&period),"device period failed");
        // Polling exclusive mode, no mixer conversion, no default endpoint usage.
        check(client->Initialize(AUDCLNT_SHAREMODE_EXCLUSIVE,0,period,period,&format.Format,nullptr),"exclusive fixture initialization failed");
        UINT32 capacity=0; check(client->GetBufferSize(&capacity),"audio buffer size failed");
        if(!capacity) throw std::runtime_error("empty audio buffer");
        ComPtr<IAudioRenderClient> render; check(client->GetService(IID_PPV_ARGS(&render)),"render service failed");
        struct StopClient { IAudioClient* client; ~StopClient(){client->Stop();} } cleanup{client.Get()};
        std::size_t offset=0; bool started=false;
        const auto end=std::chrono::steady_clock::now()+std::chrono::seconds(5)+std::chrono::milliseconds(pcm.size()*1000/384000);
        UINT32 lastPadding=0;
        for(;;) {
            if(stop_&&orderly_)throw OrderlyFixtureStop{};
            if(stop_ || recorder.failed()) throw std::runtime_error("fixture playback interrupted");
            if(std::chrono::steady_clock::now()>=end)
                throw std::runtime_error("fixture playback deadline exceeded; submitted_frames="+std::to_string(offset/8)+
                    "; padding_frames="+std::to_string(lastPadding)+"; capacity_frames="+std::to_string(capacity)+
                    "; period_100ns="+std::to_string(period));
            UINT32 padding=0; check(client->GetCurrentPadding(&padding),"audio padding failed");
            lastPadding=padding;
            if(padding>capacity) throw std::runtime_error("invalid audio padding");
            if(offset==pcm.size() && padding==0) break;
            const auto count=static_cast<UINT32>(std::min<std::size_t>(capacity-padding,(pcm.size()-offset)/8));
            if(count) {
                BYTE* target=nullptr; check(render->GetBuffer(count,&target),"audio buffer acquisition failed");
                std::memcpy(target,pcm.data()+offset,count*8);
                check(render->ReleaseBuffer(count,0),"audio buffer submission failed"); offset+=count*8;
            }
            if(!started) { check(client->Start(),"audio stream start failed"); started=true; }
            std::this_thread::sleep_for(std::chrono::milliseconds(1));
        }
    } catch(const OrderlyFixtureStop&) {
        // An explicit live Q/duration stop is not a playback fault. The capture
        // executable keeps its original interrupt-is-failure behavior.
    } catch(const std::exception& e) {
        try { error_=e.what(); } catch(...) {}
        recorder.fail("fixture playback failed (endpoint/format/deadline); host validation not earned");
    } catch(...) { recorder.fail("fixture playback failed unexpectedly"); }
    done_=true;
    if(SUCCEEDED(initialized)) CoUninitialize();
}
}
