if(CAPTURE_LINKS MATCHES "asb_core|asb_apex6")
    message(FATAL_ERROR "Capture must not link the physical-output core")
endif()
foreach(relative IN LISTS CAPTURE_SOURCES)
    file(READ "${SOURCE_ROOT}/${relative}" source)
    if(source MATCHES "apex6/|createHidTransport|Apex5Device|TriggerResetGuard|RumbleResetGuard|XInputSetState|HidD_SetOutputReport|HidD_SetFeature|GENERIC_WRITE")
        message(FATAL_ERROR "Capture isolation violation in ${relative}")
    endif()
endforeach()
message(STATUS "Capture source allowlist contains no physical-output entry points")
