if(APEX6_LINKS AND NOT APEX6_LINKS STREQUAL "APEX6_LINKS-NOTFOUND")
    message(FATAL_ERROR "Offline protocol/DSP library must have no linked dependencies")
endif()
if(CORE_LINKS MATCHES "asb_apex6")
    message(FATAL_ERROR "Physical bridge must not link the experimental offline port")
endif()
if(NOT OFFLINE_LINKS STREQUAL "asb_apex6_offline")
    message(FATAL_ERROR "Offline preview may link only the pure codec/DSP library")
endif()
list(APPEND APEX6_SOURCES src/apex6/Gpa6.h src/apex6/GripDsp.h src/apex6/offline_main.cpp)
foreach(relative IN LISTS APEX6_SOURCES)
    if(NOT relative MATCHES "^src/apex6/")
        message(FATAL_ERROR "Unexpected offline source: ${relative}")
    endif()
    file(READ "${SOURCE_ROOT}/${relative}" source)
    if(source MATCHES "windows.h|platform/|dualsense/|capture/|CreateFile|HidD_|WriteFile|DeviceIoControl|LoadLibrary|XInput|system\\(")
        message(FATAL_ERROR "Offline isolation violation in ${relative}")
    endif()
endforeach()
message(STATUS "Apex6 codec/DSP has no physical or virtual device transport")
