foreach(links IN ITEMS "${CORE_LINKS}" "${CAPTURE_LINKS}")
    if(links MATCHES "asb_apex6_live|asb_apex6_live_windows")
        message(FATAL_ERROR "Live output leaked into production/capture link graph")
    endif()
endforeach()
if(NOT LIVE_LINKS MATCHES "asb_apex6_live_windows")
    message(FATAL_ERROR "Live executable lacks guarded native transport")
endif()
if(LIVE_LINKS MATCHES "asb_core|asb_apex6_neutral_windows")
    message(FATAL_ERROR "Live executable linked unrelated output backend")
endif()
foreach(script IN ITEMS scripts/build-installer.ps1 scripts/build-portable.ps1 installer/ApexSenseBridge.iss)
    file(READ "${SOURCE_ROOT}/${script}" text)
    if(text MATCHES "ApexSenseBridgeApex6LiveBridge")
        message(FATAL_ERROR "Experimental live executable entered packaging")
    endif()
endforeach()
