"""Extract mode reports from the local USBPcap capture (no device access)."""
import hashlib
import json
import struct
import sys
from pathlib import Path

data = Path(sys.argv[1]).read_bytes()
assert hashlib.sha256(data).hexdigest() == 'a701b3fe7cee7d29301e19660dd4efe0b7d19dbf80dbcd183ea092d72a8a1a45', 'wrong source capture'
assert data[:4] == b'\xd4\xc3\xb2\xa1', 'expected little-endian microsecond pcap'
assert struct.unpack_from('<I', data, 20)[0] == 249, 'expected USBPcap link type'
offset, number, origin = 24, 0, None
reports = []
while offset < len(data):
    sec, usec, size, original = struct.unpack_from('<IIII', data, offset)
    packet = data[offset + 16:offset + 16 + size]
    assert len(packet) == size and size == original
    offset += 16 + size
    number += 1
    timestamp = sec * 1000000 + usec
    if origin is None:
        origin = timestamp
    header = struct.unpack_from('<H', packet)[0]
    endpoint = packet[21]
    length = struct.unpack_from('<I', packet, 23)[0]
    body = packet[header:]
    if number in {203, 204, 209, 371, 373, 376, 421, 422, 425, 426, 429, 431}:
        assert length == 32 and len(body) == 32 and body[:3] == b'\x5a\xa5\x53'
        reports.append(dict(frame=number, relative_us=timestamp-origin,
                            direction='device_to_host' if endpoint & 128 else 'host_to_device',
                            usb_body_hex=body.hex(), windows_report_hex='00'+body.hex()))
result = dict(schema='asb.apex6.official-silent-fixture.v1',
              capture=Path(sys.argv[1]).name, sha256=hashlib.sha256(data).hexdigest(),
              framing='USB body is exactly 32 bytes; Windows report adds explicit report ID 00',
              reply_attribution='Not inferred: official writes were pipelined',
              physical_recovery='Unverified: operator has not checked after this capture', reports=reports)
assert len(reports) == 12, 'incomplete selected reports'
destination = Path(sys.argv[2])
destination.write_text(json.dumps(result, indent=2)+'\n', encoding='utf-8')
header = '#pragma once\n// Generated by scripts/extract_apex6_silent_fixture.py; no reply attribution inferred.\nnamespace silent_capture {\n'
header += 'inline constexpr char sha256[] = "'+result['sha256']+'";\n'
header += 'struct Report { unsigned frame; long long relativeUs; bool inbound; const char* body; const char* windows; };\ninline constexpr Report reports[] = {\n'
for r in reports:
    header += f'    {{{r["frame"]}, {r["relative_us"]}, {str(r["direction"] == "device_to_host").lower()}, "{r["usb_body_hex"]}", "{r["windows_report_hex"]}"}},\n'
header += '};\n}\n'
destination.with_suffix('.h').write_text(header, encoding='utf-8')
